language: swift
osx_image: xcode9.3
xcode_workspace: Calculator.xcworkspace # path to your xcodeproj folder
xcode_scheme: Calculator
branches:
  only:
    - master
before_install:
  - brew update
  - pod repo update
script:
  - xcodebuild -scheme Calculator -workspace Calculator.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
